server:
  port: 8862

spring:
  application:
#向注册中心注册的实例名（被系统调用的实例名，如果是集群模式 此值需要一致）
    name: eurka-client
#用于链路追踪（外部需要启动相关依赖项目）
#  zipkin:
#    base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://testnode1:8761/eureka/
      
      
